### ISSUE TITLE
When run with -m option, chinotype fails to find a PSID for a given QMID

### ISSUE THREAD

**Issue by bokov** [UTHSCSA-CIRD/chinotype#8]
Error is:

```
2017.03.20 14:01:59: Creating chi columns for PSID None
Traceback (most recent call last):
  File "./chinotype.py", line 823, in <module>
    log.info(Chi2(args=args).runQMID())
  File "./chinotype.py", line 213, in runQMID
    return self.runChi()
  File "./chinotype.py", line 504, in runChi
    cols, rows = do_log_sql(db, sql, [[p[0]] for p in pats])
  File "./chinotype.py", line 804, in do_log_sql
    cursor = cur.execute(sql, params)
cx_Oracle.DatabaseError: ORA-01008: not all variables bound

```
Apparently the self.psid variable does not get properly updated. The workaround for now is to look it up outside chinotype and explicitly specify it with the `-p` option.

**Comment by bokov** [comment]
Probably a problem with that PSID being stale, because others do work.
